data_platform:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      host: 127.0.0.1
      port: 1433
      user: sa
      password: "5656"
      database: SourceData
      schema: dbo
      encrypt: false
      trust_cert: true
